name: build-registry

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "45 */7 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/ropensci-org/makeregistry
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_GRAPHQL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: false
    steps:
    - uses: actions/checkout@v2

    - name: Build registry
      run: |
        makeregistry::make_registry()
      shell: Rscript {0}

    - name: push
      if: success() && github.ref == 'refs/heads/gh-pages'
      run: |
        echo "pushing changes to github"
        git config --global user.email "accounts+ropenscibot@ropensci.org"
        git config --global user.name "ropenscibot"
        git add registry.json raw_cm.json
        git commit -m 'registry.json updated' || exit 0
        git pull --rebase
        git push
