name: build-registry

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "45 */7 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_GRAPHQL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO_PAT: ${{ secrets.GRAPHQL_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: false
    steps:
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 2
    - name: Install makeregistry
      run: |
         pak::pkg_install("ropensci-org/makeregistry")
      shell: Rscript {0}
    - name: Build packages.json
      run: |
        makeregistry::build_ropensci_packages_json()
      shell: Rscript {0}
    - name: Build registry
      run: |
        source("inst/scripts/make_registry.R")
      shell: Rscript {0}
    - uses: actions/checkout@v2
      with:
        path: roregistry
    - name: push
      run: |
        git config --global user.email "accounts+ropenscibot@ropensci.org"
        git config --global user.name "ropenscibot"
        # go into roregistry dir, pull any changes
        cd roregistry

        # copy files into roregistry directory
        echo "copying registry files into roregistry"
        cp ../registry.json .
        cp ../raw_cm.json .

        pkgslength=$(jq .packages ../registry.json | jq length)
        if [  $pkgslength -gt 250 ]; then
          # upload new registry files to github
          echo "pushing changes to github"
          git commit --allow-empty -am 'registry.json and raw_cm.json updated'
          git push
        else
          echo "Only $pkgslength package(s), this is not good. :-("
          exit 1
        fi

        # cd back to home dir
        cd ..
