name: build-packages-file

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "2 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/ropensci-org/makeregistry
    env:
      GITHUB_PAT: ${{ secrets.ANONYMOUS_PAT }}
    steps:

    - uses: actions/checkout@v2

    - name: Build packages.json
      run: |
        makeregistry::build_ropensci_packages_json()
      shell: Rscript {0}

    - name: push
      if: success() && github.ref == 'refs/heads/gh-pages'
      run: |
        echo "pushing changes to github"
        git config --global user.email "accounts+ropenscibot@ropensci.org"
        git config --global user.name "ropenscibot"
        git add packages.json
        git commit -m 'packages.json updated' || exit 0
        git pull --rebase
        git push
